---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpuexecutioncap: 90
    cpus: 2
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"
  network:
  - ["forwarded_port", {guest: 50070, host: 57072}]
  - ["forwarded_port", {guest: 50075, host: 57079}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[hadoop::install]
      - recipe[spark::install]
      - recipe[hadoop::nn]
      - recipe[hadoop::dn]
      - recipe[hadoop::rm]
      - recipe[hadoop::nm]
      - recipe[spark::master]
      - recipe[spark::slave]
      - recipe[spark::yarn]
      #- recipe[spark::historyserver]
    attributes:
         vagrant: true
         hadoop:
            nn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            use_hadoopworks: "false"
         spark:
            user: "spark"
            master:
               public_ips: ["10.0.2.15"]
               private_ips: ["10.0.2.15"]
            slave:
               public_ips: ["10.0.2.15"]
               private_ips: ["10.0.2.15"]
            yarn:
               public_ips: ["10.0.2.15"]
               private_ips: ["10.0.2.15"]
            hadoop:
               distribution: "hadoop"
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
